# Generated by Django 4.2.3 on 2023-08-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
