# Generated by Django 4.2.3 on 2023-09-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signmodel_delete_loginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignModel',
        ),
    ]
