# Generated by Django 4.2.3 on 2023-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='tel_nomer',
            field=models.IntegerField(default=998),
        ),
    ]
