# Generated by Django 4.2.3 on 2023-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_projectmodel_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_image',
            field=models.ImageField(default='defult_img', upload_to='profileimg/'),
        ),
    ]
