# Generated by Django 4.2.3 on 2023-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profilemodel_profil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='yonalish',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend')], default='frontend', max_length=20),
        ),
    ]
