# Generated by Django 4.2.3 on 2023-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projectmodel_yonalish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15)),
                ('comment', models.TextField(max_length=150)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='yonalish',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend')], default=None, max_length=20),
        ),
    ]
