# Generated by Django 4.2.3 on 2023-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profil_image',
            field=models.ImageField(blank=True, default='static/images/images/earth-g60573cb38_1280_65m6rw4.jpg', null=True, upload_to='images/'),
        ),
    ]
