# Generated by Django 4.2.3 on 2023-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profilemodel_is_online_profilemodel_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profil_image',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='images/'),
        ),
    ]
